name: Update Fixtures Calendar

on:
  schedule:
    # Run daily at 4:00 AM UTC
    - cron: '0 4 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Update calendar
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: |
          python src/update_calendar.py
          
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update fixtures calendar [automated]
          file_pattern: fixtures.ics
